[package]
name = "binder_tokio"
authors = ["Android"]
version = "1.0.0"
edition = "2021"
rust-version = "1.67"

[dependencies]
binder = { path = "../binder" }
tokio = { version = "1.25.0", features = ["full"] }
tokio-runtime = "0.0.0"
